import Head from "next/head";
import ProductBox from "@/components/ProductBox";
import Slides from "@/components/Slides";
import PartnerBox from "@/components/PartnerBox";
import NewsBoxRebuild from "@/components/NewsBoxRebuild";
import * as request from "@/utils/request";
import { useState, useEffect, useCallback } from "react";
import SlidesProductList from "@/components/SlidesProductList";
import styles from "@/styles/Home.module.scss";

const styling = {
  paddingTop: "calc(708 / 1441 * 100%)",
};

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [data, setData] = useState([]);

  //useCallBack to help dependencies in useEffect
  const fetchData = useCallback(async () => {
    try {
      setIsLoading(true);
      const response = await request.post("home-page/search");
      setData(response?.items || []);
    } catch (err) {
      console.log(err);
    } finally {
      setIsLoading(false);
    }
  }, []);
  useEffect(() => {
    fetchData();

    //[fetchData] in dependencies need the help of useCallBack
  }, [fetchData]);
  return (
    <>
      <Head>
        <title>MH Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Slides paddingTop={styling} checkNav={false} />
        <ProductBox items={data} className={styles.productBox} isLoading={isLoading}/>
        <SlidesProductList items={data} className={styles.slidesProductList} isLoading={isLoading}/>
        <NewsBoxRebuild />
        <PartnerBox />
      </>
      
    </>
  );
}

//HOW TO SET UP NESTED LAYOUT

// Home.getLayout = function getLayout(page) {
//   return (
//   );
// };
